### PR TITLE
update snapshot repos

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by tdurieux** [comment]
gzoltar is not found

**Comment by monperrus** [comment]
In which repos is Gzoltar?

**Comment by tdurieux** [comment]
I don't know, but I know it is also in https://tdurieux.github.io/maven-repository/snapshots/

**Comment by monperrus** [comment]
https://tdurieux.github.io/maven-repository/snapshots/ gives a 404

**Comment by tdurieux** [comment]
The url is good, but gzoltar is not in my repository.

It is in this one: http://sachaproject.gforge.inria.fr/repositories/releases/

**Comment by monperrus** [comment]
Now in Jenkins: https://ci.inria.fr/sos/job/maven-repair/

**Pull request merged**
